### PR TITLE
fix(k8s): cascading deletion of pods when deleting jobs

### LINKED ISSUE #280: delete succeeded pods when delete succeeded kubenetes jobs
When a job is deleted, the succeeded pods were left in the cluster until a threshold is crossed and a gc process is triggered, according to the document here:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime

We have seen clusters flooded with thousands of pods in `succeeded` state.  It is probably harmless other than causing a little stress on the master (more records in etcd). I would like to see these pods deleted along with the succeeded job, for ease of management (`kubectl get pods` produces too many records) .

### PR DESCRIPTION
**Pull request by Charles546**
#### Description
When deleting k8s jobs, the succeeded pods were orphan'ed and left for the k8s cluster to GC them until a threshold is reached. With this change, the pods will be deleted as well.

#### This PR fixes the following issues

Fixes #280

### CODE REVIEW

File: drivers/cmd/kubernetes/main.go [hunk 1]
```diff
@@ -78,7 +78,8 @@ func deleteJob(m *dipper.Message) {
 	client := k8client.BatchV1().Jobs(nameSpace)
 	ctx, cancel := context.WithTimeout(context.Background(), driver.APITimeout*time.Second)
 	defer cancel()
-	err := client.Delete(ctx, jobName, metav1.DeleteOptions{})
+	deletePropagation := metav1.DeletePropagationForeground
```
Comment (Charles546) [inline drivers/cmd/kubernetes/main.go:81]: I think `DeletePropagationBackground` is probably better.

https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#DeletionPropagation
