### PR TITLE
fix: safe reading function for sessions map

### LINKED ISSUE #142: Daemon session map concurrent read
honeydipper panics because of the unsafe read for session map 

```
E 2020-01-17T09:01:05.808788241Z fatal error: concurrent map read and map write
E 2020-01-17T09:01:05.812132816Z 
E 2020-01-17T09:01:05.812155040Z goroutine 21847 [running]:
E 2020-01-17T09:01:05.812164374Z runtime.throw(0xb023ff, 0x21)
E 2020-01-17T09:01:05.812172904Z 	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0003b5cf0 sp=0xc0003b5cc0 pc=0x42f9e2
E 2020-01-17T09:01:05.812182117Z runtime.mapaccess2_faststr(0xa2b080, 0xc000775770, 0xc0000f7e84, 0x4, 0x2, 0x2)
E 2020-01-17T09:01:05.812209730Z 	/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc0003b5d60 sp=0xc0003b5cf0 pc=0x41498f
E 2020-01-17T09:01:05.812218755Z github.com/honeydipper/honeydipper/internal/workflow.(*Session).complete(0xc0004f6a80, 0xc0004ec6c0)
E 2020-01-17T09:01:05.812227639Z 	/build/internal/workflow/continue.go:214 +0x20b fp=0xc0003b5df0 sp=0xc0003b5d60 pc=0x97c19b
E 2020-01-17T09:01:05.812236494Z github.com/honeydipper/honeydipper/internal/workflow.(*Session).continueExec(0xc0004f6a80, 0xc0004ec6c0, 0x0, 0x0, 0x0)
E 2020-01-17T09:01:05.812269484Z 	/build/internal/workflow/continue.go:315 +0xdbf fp=0xc0003b5ed0 sp=0xc0003b5df0 pc=0x97d86f
E 2020-01-17T09:01:05.812278830Z github.com/honeydipper/honeydipper/internal/workflow.(*SessionStore).ContinueSession(0xc000464fc0, 0xc000c428ec, 0x4, 0xc0004ec6c0, 0x0, 0x0, 0x0)
E 2020-01-17T09:01:05.812287847Z 	/build/internal/workflow/store.go:72 +0x1d7 fp=0xc0003b5fa8 sp=0xc0003b5ed0 pc=0x985e17
E 2020-01-17T09:01:05.812296497Z runtime.goexit()
E 2020-01-17T09:01:05.812315347Z 	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0003b5fb0 sp=0xc0003b5fa8 pc=0x45c5a1
E 2020-01-17T09:01:05.812442030Z created by github.com/honeydipper/honeydipper/internal/service.continueSession
E 2020-01-17T09:01:05.812453671Z 	/build/internal/service/engine.go:109 +0x221
```

### PR DESCRIPTION
**Pull request by huydinhle**
#### Description
Currently, the complete function of Session struct is reading the sessions map by directly accessing it. We switch this to use IDMapGet to utilize the Mutex lock to make this operation concurrently safe

#### This PR fixes the following issues
Fixes #142

### CODE REVIEW

File: internal/workflow/continue.go [hunk 1]
```diff
@@ -211,7 +211,8 @@ func (w *Session) complete(msg *dipper.Message) {
 	}
 	dipper.Logger.Infof("[workflow] session [%s] completing with msg labels %+v", w.ID, msg.Labels)
 	if w.ID != "" {
-		if _, ok := w.store.sessions[w.ID]; ok {
+		res := dipper.IDMapGet(w.store.sessions, w.ID).(SessionHandler)
+		if res != nil {
```
Comment (Charles546) [inline internal/workflow/continue.go]: This can be written in one line in go style, or just skip the assignment just compare the return value directly. I don't think we need that variable.
```go
if ....; ... {
  ...
} 
```
or
```go
if dipper.IDMapGet(...) != nil {
  ...
}
```

Comment (huydinhle) [reply internal/workflow/continue.go]: ah let me get on that
