### PR TITLE
fix(config): regex patterns in unless_match and dollar interpolation default val with comma

### LINKED ISSUE #187: dollar interpolation default value losing commas
When using dollar interpolations, we can specify a default value like this.

```
  var: $ctx.possible_key1,ctx.possible_key2,"default value as a string"
```

However, if the default value has comma "," in it, the comma was lost somehow. For example,

```
  var: $ctx.key1,ctx.key2,`this is a message, with comma`
```

If `key1` and `key2` are missing, the `var` supposed to be `this is a message, with comma`, but it actually ends up as `this is a message with comma`.

### LINKED ISSUE #188: regex patterns in unless_match field of workflows are not working
Regular expressions are mostly parsed when the configurations are loaded.  Regex patterns in top level workflows' fields such as `if_match`, `unless_match` are parsed, however, if there are embedded workflows in the `steps` or `threads`, then their patterns are not parsed.

Top level workflows mean any workflows defined with a name, and any workflows defined in a rule.

For example,

Below works
```
workflows:
  test-workflow:
    if_match:
      output: :regex:^success$
    call_workflow: dosomething
```

But the following doesn't

```
workflows:
  test-workflow:
    steps:
      - unless_match:
           output: regex:^success$
         call_workflow: dosomething
      - call_workflow: notify
```

### PR DESCRIPTION
**Pull request by Charles546**
#### Description

 * Parsing regex pattern in `unless_match` workflow field
 * Ensuring dollar interpolation not omit the commas in default value

#### This PR fixes the following issues
Fixes #187 
Fixes #188

### CODE REVIEW

**Comment by Charles546** [comment]
We will need to do rebase merge instead of squash.

File: pkg/dipper/interpolation.go [hunk 1]
```diff
@@ -90,7 +90,11 @@ func Interpolate(source interface{}, data interface{}) interface{} {
 
 				if quote != 0 {
 					if key[len(key)-1] == quote {
-						defaultVal += key[:len(key)-1]
+						if defaultVal == "" {
+							defaultVal += key[:len(key)-1]
+						} else {
+							defaultVal += "," + key[:len(key)-1]
```
Comment (wyardley) [inline pkg/dipper/interpolation.go]: would `join()` make sense instead?
