### PR TITLE
fix(config): avoid concurrent map write in config

### LINKED ISSUE #354: daemon crash with "concurrent map write" in collapseFunction
Daemon crashes in `collapseFunction` call in `operator` service with `concurrent map write` error message.

```
 Error
2020-12-09 11:37:42.509 PST
fatal error: concurrent map writes
Info
2020-12-09 11:37:42.509 PST
19:37:42.509 daemon.operatorRoute ▶ INFO 8362 [operator] routing message rpc.return
Error
2020-12-09 11:37:42.509 PST
fatal error: concurrent map writes
Info
2020-12-09 11:37:42.509 PST
19:37:42.509 daemon.operatorRoute ▶ INFO 8361 [operator] routing message rpc.return
Error
2020-12-09 11:37:42.517 PST
Error
2020-12-09 11:37:42.517 PST
goroutine 191346 [running]:
Error
2020-12-09 11:37:42.517 PST
runtime.throw(0xd8ccc6, 0x15)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00086cfd0 sp=0xc00086cfa0 pc=0x437cf2
Error
2020-12-09 11:37:42.517 PST
runtime.mapassign(0xc90260, 0xc001084210, 0xc0008c2670, 0xc0004dc780)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/runtime/map.go:676 +0x5a7 fp=0xc00086d050 sp=0xc00086cfd0 pc=0x411cc7
Error
2020-12-09 11:37:42.517 PST
reflect.mapassign(0xc90260, 0xc001084210, 0xc0008c2670, 0xc001177580)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/runtime/map.go:1319 +0x3f fp=0xc00086d080 sp=0xc00086d050 pc=0x4666bf
Error
2020-12-09 11:37:42.517 PST
reflect.Value.SetMapIndex(0xc90260, 0xc001084210, 0x15, 0xc557e0, 0xc0008c2670, 0x98, 0xc7b660, 0xc001177580, 0x94)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/reflect/value.go:1696 +0x27c fp=0xc00086d100 sp=0xc00086d080 pc=0x4a069c
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/pkg/dipper.RecursiveWithPrefix(0xc90260, 0xc001084210, 0x0, 0x0, 0xc557e0, 0xc0008c2670, 0xc557e0, 0xc000a7d080, 0xc00086d518)
Error
2020-12-09 11:37:42.517 PST
/build/pkg/dipper/mapUtils.go:186 +0x738 fp=0xc00086d288 sp=0xc00086d100 pc=0x840d38
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/pkg/dipper.RecursiveWithPrefix(0x0, 0x0, 0x0, 0x0, 0xc557e0, 0xe6eef0, 0xc90260, 0xc001084210, 0xc00086d518)
Error
2020-12-09 11:37:42.517 PST
/build/pkg/dipper/mapUtils.go:157 +0x472 fp=0xc00086d410 sp=0xc00086d288 pc=0x840a72
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/pkg/dipper.Recursive(...)
Error
2020-12-09 11:37:42.517 PST
/build/pkg/dipper/mapUtils.go:137
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/internal/service.collapseFunction(0xc00086d810, 0xc00086d8b0, 0xc0012888a0, 0xc, 0xc0001cba88, 0x1, 0x0, 0xea5b40)
Error
2020-12-09 11:37:42.517 PST
/build/internal/service/operator.go:200 +0x6a5 fp=0xc00086d6e8 sp=0xc00086d410 pc=0xbc9985 
```

### PR DESCRIPTION
**Pull request by Charles546**
#### Description
The concurrent map writes are usually caused by updating to
the configuration when the services decrypt some piece of
data, or a regexp is parsed.

This commit changes how the configuration handles the updating
of the configs. Instead of, delaying the decryption and regexp
parsing to later time, the config module will take care of them
at the startup of the services.

The config process will be divided into multiple stages, and
all the services will be synchronized to use the configuration
according to the stages. Also introduced a `RawData` to holds
the raw data for use in rollback and re-decrypt, if necessary.
The configuration becomes readonly to services.

 * Add stages and the synchronizing variables to config
 * Put decryption and regexp parsing into stages
 * Remove scattered calls for decryption and regexp parsing
 * Add a `RawData` in config to keep `Rollback` working
 * Fixing tests accordingly

#### This PR fixes the following issues
Fixes #354

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -109,48 +171,132 @@ func (c *Config) Refresh() {
...
 
 		return nil, false
 	}
 
-	dipper.Recursive(c.DataSet.Workflows, processor)
-	dipper.Recursive(c.DataSet.Rules, processor)
-	dipper.Recursive(c.DataSet.Contexts, dipper.RegexParser)
+	dipper.Logger.Debugf("[config] recursive processing workflows ...")
+	dipper.Recursive(target.Workflows, processor)
+	dipper.Logger.Debugf("[config] recursive processing rules ...")
```
Comment (wyardley) [inline internal/config/config.go:278]: should these be 'recursively processing ...'?

**Review by rebeccatang16 — APPROVED** [review]
