### PR TITLE
fix(config): function export should arrange parent subsystem data properly

### LINKED ISSUE #269: Function export is broken for subsystem calls
A `system` can have subsystems in Honeydipper.  It is the way that the private system data can be exposed to other systems. When calling a function belong to a subsystem, the parent system data should be added to the the child system and accessed through key `parent`. This should also be done when interpolating the function exports, because the parameters are also used for interpolation.

The function export feature introduced in `1.5.0` has a bug that the subsystem data was not arranged properly.

### PR DESCRIPTION
**Pull request by Charles546**
#### Description
* rewrite the `ExportFunctionContext` func to ensure the parent/subsystem data are arranged
* allow merging and deep copying nil
* more tests for the the changes

#### This PR fixes the following issues

Fixes #269

### CODE REVIEW

File: internal/config/function_export.go [hunk 1]
```diff
@@ -25,24 +25,21 @@ func ExportFunctionContext(s *System, f *Function, envData map[string]interface{
...
+				dipper.Logger.Panicf("[operator] sysData is not a map")
 			}
 		}
 
-		var sysData map[string]interface{}
+		// the parameters need to be squashed before interpolation
+		// we will also need to provide the squashed sysData for interpolation
+		// the outter parameters should override inner parameters, but
+		// the inner sysData should override outter sysData
+		outterParam, _ := envData["params"]
```
Comment (wyardley) [inline internal/config/function_export.go:40]: nit: typo (outer)

File: internal/config/function_export_test.go [hunk 2]
```diff
@@ -240,3 +237,147 @@ func TestFunctionExportWithSquashedSysData(t *testing.T) {
 
 	assert.Equal(t, "http://value1.value3/test/path1?q1=value4", result["url"])
 }
+
+func TestFunctionExportWithSubsystem(t *testing.T) {
+	cfg := Config{
+		DataSet: &DataSet{
+			Systems: map[string]System{
+				"outter": System{
```
Comment (wyardley) [inline internal/config/function_export_test.go:245]: Same

**Comment by Charles546** [comment]
Just refactored again, and I feel that this version make sense.  I hope this is more readable.  😄
