### PR TITLE
fix(web): json Payload use interface to support top level array

### LINKED ISSUE #92: Web driver return payload json not supporting top level arrays
If a web request receives a json object that the top level is an array, it will fail to load the json object.  The reason is that the driver is assuming the json can be loaded into a `map[string]interface{}`. We should change that to a `interface{}`.

### PR DESCRIPTION
**Pull request by cynful**
#### Description
json Payload uses interface to support top level array

#### This PR fixes the following issues
Fixes #92

### CODE REVIEW

File: drivers/cmd/web/main_test.go [hunk 1]
```diff
@@ -50,6 +50,33 @@ func TestSendRequest(t *testing.T) {
 	response := <-request.Reply
 	assert.Equal(t, "200", response.Payload.(map[string]interface{})["status_code"])
 	assert.NotContains(t, response.Labels, "error")
+	foo, _ := response.Payload.(map[string]interface{})["json"].(map[string]interface{})["foo"]
+	assert.Equal(t, "bar", foo, "JSON data miss-match")
```
Comment (wyardley) [inline drivers/cmd/web/main_test.go]: Should be mismatch. And maybe something a little more descriptive than `foo` here?
